version: "3"

services:
  nginx:
    image: nginx:1.15.6-alpine
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./etc/nginx/keys:/etc/nginx/keys:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./etc/nginx/common:/etc/nginx/common:ro
      - ./dist/public:/public:ro

    # https://github.com/docker/for-linux/issues/264#issuecomment-385698947
    command:
      - /bin/sh
      - -c 
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && exec nginx -g 'daemon off;'

