#!/bin/bash
# :vim ft=sh

# rootでファイルが作成されるのを防ぐため
bindfs_start() {
	# ローカルで動いているDockerならKernel Versionが自分と同じはずである
	if [ "$(docker info --format '{{.KernelVersion}}')" == "$(uname -r)" ]; then
		# Linux
		VOL_TARGET=$VOL_NAME
	
		if [ -z $(docker plugin ls --format '{{.Name}}' | grep 'lebokus/bindfs') ]; then
			echo "Install docker plugin lebokus/bindfs"
			docker plugin install lebokus/bindfs
		fi
		
		if [ $(docker plugin ls --format '{{.Name}} {{.Enabled}}' | grep lebokus/bindfs:latest | awk '{print $2}') == "false" ]; then
			echo "Set Enable plugin lebokus/bindfs"
			docker plugin enable lebokus/bindfs
		fi
	
		docker volume create \
		    -d lebokus/bindfs \
		    -o sourcePath=$(pwd) \
		    -o map=$(id -u)/0:@$(id -g)/@0 \
			$VOL_NAME > /dev/null
	else
		# Docker for Macなどでは不要
		VOL_TARGET=$(pwd)
	fi
}

# クリーンアップ
bindfs_finish() {
	if [ -n "$(docker volume ls --format='{{.Name}}' | grep $VOL_NAME )" ]; then
		docker volume rm $VOL_NAME > /dev/null
	fi
}

# Docker ImageをPull
pull_image() {
	if [ -z "$(docker image ls --format="{{.Repository}}:{{.Tag}}" | grep "$APP_NAME")" ]; then
		docker pull $APP_NAME
	fi
}

